# Generated by Django 5.2.8 on 2026-01-26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('message_count', models.PositiveIntegerField(default=0, help_text='Number of messages in this conversation')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent message', null=True)),
                ('journey', models.ForeignKey(blank=True, help_text='The journey/condition this conversation is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='journeys.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
