# Generated by Django 5.2.8 on 2026-01-16 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conv_id', models.CharField(max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('thread_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(default='gpt-4', max_length=100)),
                ('journey', models.ForeignKey(blank=True, help_text='The journey/condition this conversation is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='journeys.journey')),
            ],
        ),
    ]
