# Generated by Django 5.2.8 on 2026-01-26

from django.db import migrations


def setup_checkpointer(apps, schema_editor):
    """Set up the LangGraph checkpointer tables."""
    from langgraph.checkpoint.postgres import PostgresSaver
    import environ

    env = environ.Env()
    conn_string = env.str("DATABASE_URL")

    with PostgresSaver.from_conn_string(conn_string) as checkpointer:
        checkpointer.setup()


def teardown_checkpointer(apps, schema_editor):
    """Remove the LangGraph checkpointer tables."""
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS checkpoints CASCADE;")
        cursor.execute("DROP TABLE IF EXISTS checkpoint_writes CASCADE;")
        cursor.execute("DROP TABLE IF EXISTS checkpoint_blobs CASCADE;")


class Migration(migrations.Migration):

    dependencies = [
        ('llmchat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(setup_checkpointer, teardown_checkpointer),
    ]
