# Generated by Django 5.2.8 on 2026-01-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmchat', '0003_langgraph_checkpointer'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent message', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='message_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of messages in this conversation'),
        ),
    ]
