# Generated by Django 5.2.8 on 2026-01-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llmchat', '0004_add_conversation_analytics_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='conv_id',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='thread_id',
        ),
    ]
