# Generated by Django 5.2.8 on 2026-01-07 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0100_load_journeys'),
        ('llmchat', '0100_langgraph_checkpointer'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='journey',
            field=models.ForeignKey(blank=True, help_text='The journey/condition this conversation is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='journeys.journey'),
        ),
    ]
