# Generated by Django 5.2.8 on 2026-01-26 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journeys', '0002_journeyresponse_conversation'),
        ('llmchat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='summaries/%Y/%m/')),
                ('narrative_summary', models.TextField(help_text='LLM-generated narrative summary text')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='llmchat.conversation')),
            ],
            options={
                'verbose_name_plural': 'Conversation summaries',
            },
        ),
        migrations.CreateModel(
            name='ConversationPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional context about this conversation point')),
                ('curiosity_prompt', models.TextField(blank=True, help_text="First-person curiosity text shown to users (e.g., 'I'd like to understand what matters most to you')")),
                ('system_message_template', models.TextField(help_text="Message to add to conversation when this point is initiated. Example: 'I'd like to understand your goals for treatment. Are there activities you've been unable to do because of your back pain?'")),
                ('semantic_keywords', models.JSONField(default=list, help_text="Keywords and phrases that indicate this topic has been discussed. Used for semantic memory extraction. Example: ['treatment goals','what I hope to achieve','activities I miss']")),
                ('confidence_threshold', models.FloatField(default=0.7, help_text='Confidence threshold (0-1) for considering this point addressed')),
                ('elicitation_goals', models.JSONField(default=list, help_text="List of specific information goals the AI should try to achieve. Example: ['Identify 2-3 activities patient wants to resume', 'Understand their timeline expectations']")),
                ('example_questions', models.JSONField(default=list, help_text='Example questions the AI can use or adapt when initiating this point. These guide the AI toward more effective elicitation.')),
                ('suggested_questions', models.JSONField(default=list, help_text="Question starters shown as clickable bubbles to help users ask questions. Example: ['Can you tell me more about...', 'What are the risks of...']")),
                ('completion_criteria', models.JSONField(default=dict, help_text="Criteria for considering this point addressed. Example: {'activities_identified': true, 'timeline_discussed': true}")),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_points', to='journeys.journey')),
            ],
            options={
                'ordering': ['sort_order', 'slug'],
                'unique_together': {('journey', 'slug')},
            },
        ),
    ]
