# Generated by Django 5.2.8 on 2025-12-23 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journeys', '0100_load_journeys'),
        ('memory', '0001_setup_postgres_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional context about this conversation point')),
                ('system_message_template', models.TextField(help_text="Message to add to conversation when this point is initiated. Example: 'I'd like to understand your goals for treatment. Are there activities you've been unable to do because of your back pain?'")),
                ('semantic_keywords', models.JSONField(default=list, help_text="Keywords and phrases that indicate this topic has been discussed. Used for semantic memory extraction. Example: ['treatment goals','what I hope to achieve','activities I miss']")),
                ('confidence_threshold', models.FloatField(default=0.7, help_text='Confidence threshold (0-1) for considering this point addressed')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_points', to='journeys.journey')),
            ],
            options={
                'ordering': ['sort_order', 'slug'],
                'unique_together': {('journey', 'slug')},
            },
        ),
    ]
