# Generated by Django 5.2.8 on 2026-01-26

from django.db import migrations


def setup_store(apps, schema_editor):
    """Set up the LangGraph memory store tables."""
    from langgraph.store.postgres import PostgresStore
    import environ

    env = environ.Env()
    conn_string = env.str("DATABASE_URL")

    with PostgresStore.from_conn_string(conn_string) as store:
        store.setup()


def teardown_store(apps, schema_editor):
    """Remove the LangGraph store tables."""
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS store CASCADE;")


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(setup_store, teardown_store),
    ]
