# Generated by Django 5.2.8 on 2026-01-16 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmchat', '0003_langgraph_checkpointer'),
        ('memory', '0002_setup_postgres_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='summaries/%Y/%m/')),
                ('narrative_summary', models.TextField(help_text='LLM-generated narrative summary text')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='llmchat.conversation')),
            ],
            options={
                'verbose_name_plural': 'Conversation summaries',
            },
        ),
    ]
