# Generated by Django 5.2.8 on 2026-01-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_conversationsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationpoint',
            name='completion_criteria',
            field=models.JSONField(default=dict, help_text="Criteria for considering this point addressed. Example: {'activities_identified': true, 'timeline_discussed': true}"),
        ),
        migrations.AddField(
            model_name='conversationpoint',
            name='elicitation_goals',
            field=models.JSONField(default=list, help_text="List of specific information goals the AI should try to achieve. Example: ['Identify 2-3 activities patient wants to resume', 'Understand their timeline expectations']"),
        ),
        migrations.AddField(
            model_name='conversationpoint',
            name='example_questions',
            field=models.JSONField(default=list, help_text='Example questions the AI can use or adapt when initiating this point. These guide the AI toward more effective elicitation.'),
        ),
    ]
