# Generated by Django 5.2.8 on 2026-01-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0004_add_elicitation_fields_to_conversation_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationpoint',
            name='curiosity_prompt',
            field=models.TextField(blank=True, help_text="First-person curiosity text shown to users (e.g., 'I'd like to understand what matters most to you')"),
        ),
    ]
