# Generated by Django 5.2.8 on 2026-01-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0005_conversationpoint_curiosity_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationpoint',
            name='suggested_questions',
            field=models.JSONField(default=list, help_text="Question starters shown as clickable bubbles to help users ask questions. Example: ['Can you tell me more about...', 'What are the risks of...']"),
        ),
    ]
