# Generated by Django 5.2.8 on 2026-01-26 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journeys', '0003_load_journeys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='documents/')),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('text_content', models.TextField(blank=True, default='')),
                ('chunk_size', models.PositiveIntegerField(default=500)),
                ('chunk_overlap', models.PositiveIntegerField(default=50)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, default='', help_text='Error message if processing failed')),
                ('processing_duration_seconds', models.FloatField(blank=True, help_text='Time taken to process the document', null=True)),
                ('chroma_collection', models.CharField(blank=True, default='', max_length=255)),
                ('vector_count', models.PositiveIntegerField(default=0)),
                ('embedding_model', models.CharField(blank=True, default='', help_text="The embedding model used (e.g., 'openai:text-embedding-3-small')", max_length=100)),
                ('journeys', models.ManyToManyField(blank=True, help_text='Journeys this evidence applies to. Empty = universal.', related_name='evidence_documents', to='journeys.journey')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('text_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='evidence.document')),
            ],
            options={
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
