# Generated by Django 5.2.8 on 2026-01-25 16:17

import django.db.models.deletion
from django.db import migrations, models


def migrate_is_processed_to_status(apps, schema_editor):
    """Migrate is_processed boolean to processing_status enum."""
    Document = apps.get_model("evidence", "Document")
    # Documents that were processed become 'completed'
    Document.objects.filter(is_processed=True).update(processing_status="completed")
    # Documents that were not processed stay as 'pending' (the default)


def reverse_migrate_status_to_is_processed(apps, schema_editor):
    """Reverse migration: processing_status back to is_processed."""
    Document = apps.get_model("evidence", "Document")
    Document.objects.filter(processing_status="completed").update(is_processed=True)
    Document.objects.exclude(processing_status="completed").update(is_processed=False)


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0002_initial"),
        ("journeys", "0005_change_journeyresponse_fk_to_protect"),
    ]

    operations = [
        # First, add the new fields
        migrations.AddField(
            model_name="document",
            name="embedding_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The embedding model used (e.g., 'openai:text-embedding-3-small')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="journey",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this evidence only applies to this journey's RAG retrieval",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evidence_documents",
                to="journeys.journey",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="processing_duration_seconds",
            field=models.FloatField(
                blank=True, help_text="Time taken to process the document", null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="processing_error",
            field=models.TextField(
                blank=True, default="", help_text="Error message if processing failed"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        # Migrate data from is_processed to processing_status
        migrations.RunPython(
            migrate_is_processed_to_status,
            reverse_migrate_status_to_is_processed,
        ),
        # Now safe to remove old fields
        migrations.RemoveField(
            model_name="document",
            name="is_processed",
        ),
        migrations.RemoveField(
            model_name="documentchunk",
            name="embedding_cached",
        ),
    ]
