# Generated by Django 5.2.8 on 2025-12-04 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llmchat', '0100_langgraph_checkpointer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('subdomain', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('onboarding_questions', models.JSONField(default=list)),
                ('welcome_message', models.TextField(default='')),
                ('system_prompt_template', models.TextField(blank=True, help_text="System prompt template with placeholders matching question IDs. Example: 'The patient has had back pain for {duration} with {pain_level} severity.'")),
                ('hero_image', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#0066cc', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='JourneyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('responses', models.JSONField(default=dict)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_response', to='llmchat.conversation')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responses', to='journeys.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='journey_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'journey')},
            },
        ),
    ]
