# Generated by Django 5.2.8 on 2026-01-16 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('onboarding_questions', models.JSONField(default=list)),
                ('welcome_message', models.TextField(default='')),
                ('system_prompt_template', models.TextField(blank=True, help_text="System prompt template with placeholders matching question IDs. Example: 'The patient has had back pain for {duration} with {pain_level} severity.'")),
                ('hero_image', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#0066cc', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='JourneyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('responses', models.JSONField(default=dict)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JourneyOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('benefits', models.JSONField(default=list)),
                ('drawbacks', models.JSONField(default=list)),
                ('typical_timeline', models.CharField(blank=True, help_text="Expected duration or timeline, e.g., '6-12 weeks'", max_length=255)),
                ('success_rate', models.CharField(blank=True, help_text="Typical success rate, e.g., '70-80%'", max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='journeys.journey')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
