# Generated by Django 5.2.8 on 2026-01-16 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journeys', '0001_initial'),
        ('llmchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyresponse',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_response', to='llmchat.conversation'),
        ),
        migrations.AddField(
            model_name='journeyresponse',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responses', to='journeys.journey'),
        ),
        migrations.AddField(
            model_name='journeyresponse',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='journeys.journeyoption'),
        ),
    ]
