# Generated by Django 5.2.8 on 2026-01-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0001_initial'),
        ('llmchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyresponse',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journey_response', to='llmchat.conversation'),
        ),
    ]
