# Generated by Django 5.2.8 on 2026-01-16 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journeys', '0002_add_conversation_foreign_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='journey_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='journeyoption',
            unique_together={('journey', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='journeyresponse',
            unique_together={('user', 'journey')},
        ),
    ]
