# Generated by Django 5.2.8 on 2026-01-26

from django.db import migrations


def load_journeys(apps, schema_editor):
    """Load journey configurations from JSON files."""
    from django.core.management import call_command
    call_command("load_journeys")


def reverse_load_journeys(apps, schema_editor):
    """No-op reverse - journeys would need manual cleanup."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_journeyresponse_conversation'),
        ('memory', '0001_initial'),  # Needs ConversationPoint model
    ]

    operations = [
        migrations.RunPython(load_journeys, reverse_load_journeys),
    ]
