# Generated by Django 5.2.8 on 2026-01-27 20:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0003_load_journeys'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionAid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('aid_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('external_video', 'External Video (YouTube/Vimeo)'), ('infographic', 'Infographic'), ('diagram', 'Diagram')], max_length=20)),
                ('file', models.FileField(blank=True, upload_to='decision_aids/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='decision_aids/thumbs/')),
                ('external_url', models.URLField(blank=True)),
                ('description', models.TextField(help_text='Description of what this aid shows. Provided to the LLM.')),
                ('alt_text', models.CharField(blank=True, max_length=500)),
                ('transcript', models.TextField(blank=True, help_text='Video transcript')),
                ('display_context', models.TextField(blank=True, help_text="When should this be shown? e.g., 'When explaining PT benefits'")),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journeys', models.ManyToManyField(blank=True, help_text='Journeys this aid applies to. Empty = universal.', related_name='decision_aids', to='journeys.journey')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
