# Generated by Django 5.2.8 on 2026-01-25 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0004_load_journeys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyresponse',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='journeys.journey'),
        ),
        migrations.AlterField(
            model_name='journeyresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journey_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
