# Generated by Django 5.2.8 on 2026-01-26 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0006_change_user_cascade_delete'),
        ('llmchat', '0005_remove_conv_id_thread_id_use_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyresponse',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journey_response', to='llmchat.conversation'),
        ),
    ]
